version: '2'

services:
  react:
    build: ./reactjs
    volumes:
      - .:/usr/src/app
    environment:
      - VIRTUAL_HOST=reactjs.arcadas.com
      - VIRTUAL_PORT=3000
    expose:
      - 3000
    networks:
      - proxy
    user: '1000:1000'
    stdin_open: true
    command: sh -c "npm install && npm run start"

networks:
  proxy:
    external: true
